name: map_of_points
description: "A Flutter application for parsing and visualizing flight logs."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.11.0
  auto_route: ^10.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^8.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_map: ^6.1.1
  latlong2: ^0.9.1

dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
